### ISSUE TITLE
Web-interface controller lag

### ISSUE THREAD

**Issue by guslauer** [justasAtGU/dit168#21]
Sometimes the controller gets stuck for a second or two. Stuck in the sense that according to 'Isabelle's animation', the key gets "stuck" thus its release is delayed. Consequently, commands such as stop is a bit delayed which is. sometimes, noticeable when driving the car. It does not, however, happen often, but it is there. It is independent from which platform the web-interface is hosted on, i.e. it does not matter if the controller is ran on the actual car or locally on your computer.

**Comment by Jeberlen** [comment]
I will try to look into some optimization options for the browser

**Comment by Jeberlen** [comment]
I can't replicate this behavior. I will label it as an enhancement.

**Comment by guslauer** [comment]
Only happens in Mozilla Firefox on my machine. Chrome/Chromium works fine.
