### ISSUE TITLE
CMakeLists.txt in root folder does not build

### ISSUE THREAD

**Issue by chrberger** [justasAtGU/dit168#8]
I found a CMakeLists.txt in the repository root folder that did not build successfully.

**Comment by guslauer** [comment]
@chrberger We all seem to be able to build the CMakeLists.txt in question. That is, however, after we install the required libraries, in our case vera++ and Doxygen. Are we doing some fundamentally wrong? We tried to find a command for CMAKE where it automatically installed the libraries/dependencies but were unable to do so.

Our Travis is able to run the CMAKE although we have a 'before_install' command with the required libraries in the `.yml`

**Comment by chrberger** [comment]
I could not build on my machine as in my native Ubuntu 16.04LTS, the tools vera++ and doxygen were not present (I only have them in my Docker-ized toolchains). The information what needed to be present on the machine was missing in the README.md (or how/when to use the root folder's CMakeLists.txt).

**Comment by Jeberlen** [comment]
Thank you for the comment, the root CMakeLists.txt now targets the src/FirstSub/Communicator directory, with preparations to target the src and test directories when we actually start writing more code. make and make test now builds and runs.
